### ISSUE TITLE
can't run python script

### ISSUE THREAD

**Issue by ghost** [hackyourlife/extrememusic-downloader#3]
When I try to run the script it displays a syntax error (invalid syntax).
Tested on Ubuntu 22.04.

**Comment by hackyourlife** [comment]
Unfortunately the entire extreme music website and how it works internally changed years ago and as a result this script doesn't work anymore anyway.

**Comment by eliasehmann** [comment]
any chance that you will rewrite the code? are there any alternatives? I'd really like to use it
